# Generated by Django 4.0.2 on 2022-02-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.CharField(default='https://bit.ly/3HKRFtz', max_length=255),
            preserve_default=False,
        ),
    ]
